set_property PACKAGE_PIN V10 [get_ports {SW_SEL[3]}]
set_property PACKAGE_PIN U11 [get_ports {SW_SEL[2]}]
set_property PACKAGE_PIN U12 [get_ports {SW_SEL[1]}]
set_property PACKAGE_PIN H6 [get_ports {SW_SEL[0]}]
set_property PACKAGE_PIN T10 [get_ports {DISP_7SEG[6]}]
set_property PACKAGE_PIN R10 [get_ports {DISP_7SEG[5]}]
set_property PACKAGE_PIN K16 [get_ports {DISP_7SEG[4]}]
set_property PACKAGE_PIN K13 [get_ports {DISP_7SEG[3]}]
set_property PACKAGE_PIN P15 [get_ports {DISP_7SEG[2]}]
set_property PACKAGE_PIN T11 [get_ports {DISP_7SEG[1]}]
set_property PACKAGE_PIN L18 [get_ports {DISP_7SEG[0]}]
set_property PACKAGE_PIN T13 [get_ports SW_EM_ON]
set_property PACKAGE_PIN R16 [get_ports SW_EM_OFF]
set_property PACKAGE_PIN N15 [get_ports DISP_LED_DN]
set_property PACKAGE_PIN N16 [get_ports DISP_LED_UP]
set_property PACKAGE_PIN P18 [get_ports BTN_DN]
set_property PACKAGE_PIN N17 [get_ports BTN_EL]
set_property PACKAGE_PIN M18 [get_ports BTN_UP]
set_property PACKAGE_PIN P17 [get_ports BTN_NS]
set_property PACKAGE_PIN M17 [get_ports BTN_RST]

set_property IOSTANDARD LVCMOS18 [get_ports BTN_RST]
set_property IOSTANDARD LVCMOS18 [get_ports BTN_UP]
set_property IOSTANDARD LVCMOS18 [get_ports DISP_LED_DN]
set_property IOSTANDARD LVCMOS18 [get_ports DISP_LED_UP]
set_property IOSTANDARD LVCMOS18 [get_ports SW_EM_OFF]
set_property IOSTANDARD LVCMOS18 [get_ports SW_EM_ON]
set_property IOSTANDARD LVCMOS18 [get_ports {DISP_7SEG[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DISP_7SEG[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DISP_7SEG[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DISP_7SEG[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DISP_7SEG[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DISP_7SEG[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DISP_7SEG[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW_SEL[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW_SEL[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW_SEL[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SW_SEL[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports BTN_DN]
set_property IOSTANDARD LVCMOS18 [get_ports BTN_EL]
set_property IOSTANDARD LVCMOS18 [get_ports BTN_NS]

set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS18} [get_ports CLK100MHZ]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports CLK100MHZ]

set_property PACKAGE_PIN C12 [get_ports HARD_RESET]
set_property IOSTANDARD LVCMOS18 [get_ports HARD_RESET]

set_property PACKAGE_PIN K15 [get_ports LED_TRAV]
set_property IOSTANDARD LVCMOS18 [get_ports LED_TRAV]
set_property PACKAGE_PIN H17 [get_ports LED_DO]
set_property IOSTANDARD LVCMOS18 [get_ports LED_DO]

set_property PACKAGE_PIN V11 [get_ports {LED_BTN[8]}]
set_property PACKAGE_PIN V12 [get_ports {LED_BTN[7]}]
set_property PACKAGE_PIN V14 [get_ports {LED_BTN[6]}]
set_property PACKAGE_PIN V15 [get_ports {LED_BTN[5]}]
set_property PACKAGE_PIN T16 [get_ports {LED_BTN[4]}]
set_property PACKAGE_PIN U14 [get_ports {LED_BTN[3]}]
set_property PACKAGE_PIN T15 [get_ports {LED_BTN[2]}]
set_property PACKAGE_PIN V16 [get_ports {LED_BTN[1]}]
set_property PACKAGE_PIN U16 [get_ports {LED_BTN[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED_BTN[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED_BTN[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED_BTN[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED_BTN[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED_BTN[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED_BTN[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED_BTN[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED_BTN[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LED_BTN[0]}]

set_property CFGBVS Vcco [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

set_property PACKAGE_PIN R11 [get_ports DISP_LED_NS_UP]
set_property PACKAGE_PIN M16 [get_ports DISP_LED_NS_DN]
set_property PACKAGE_PIN R12 [get_ports DISP_LED_RST_DN]
set_property PACKAGE_PIN G14 [get_ports DISP_LED_RST_UP]
set_property IOSTANDARD LVCMOS18 [get_ports DISP_LED_NS_DN]
set_property IOSTANDARD LVCMOS18 [get_ports DISP_LED_NS_UP]
set_property IOSTANDARD LVCMOS18 [get_ports DISP_LED_RST_DN]
set_property IOSTANDARD LVCMOS18 [get_ports DISP_LED_RST_UP]

set_property PACKAGE_PIN J13 [get_ports LED_E_EN]
set_property IOSTANDARD LVCMOS18 [get_ports LED_E_EN]
set_property DRIVE 8 [get_ports DISP_LED_UP]
set_property DRIVE 8 [get_ports DISP_LED_RST_UP]
set_property DRIVE 8 [get_ports DISP_LED_RST_DN]
set_property DRIVE 8 [get_ports DISP_LED_NS_UP]
set_property DRIVE 8 [get_ports DISP_LED_NS_DN]
set_property DRIVE 8 [get_ports DISP_LED_DN]

set_property PACKAGE_PIN U13 [get_ports {OUT_7SEG_MASK[7]}]
set_property PACKAGE_PIN K2 [get_ports {OUT_7SEG_MASK[6]}]
set_property PACKAGE_PIN T14 [get_ports {OUT_7SEG_MASK[5]}]
set_property PACKAGE_PIN P14 [get_ports {OUT_7SEG_MASK[4]}]
set_property PACKAGE_PIN J14 [get_ports {OUT_7SEG_MASK[3]}]
set_property PACKAGE_PIN T9 [get_ports {OUT_7SEG_MASK[2]}]
set_property PACKAGE_PIN J18 [get_ports {OUT_7SEG_MASK[1]}]
set_property PACKAGE_PIN J17 [get_ports {OUT_7SEG_MASK[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OUT_7SEG_MASK[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OUT_7SEG_MASK[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OUT_7SEG_MASK[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OUT_7SEG_MASK[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OUT_7SEG_MASK[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OUT_7SEG_MASK[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OUT_7SEG_MASK[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OUT_7SEG_MASK[0]}]
